### ISSUE TITLE
"leegnu" submit gives 500 error

### ISSUE THREAD

**Issue by jgroenen** [TiltShiftNL/cleanstreet#6]
"/.*leeg.*" route gives a 500 error on submit

**Comment by milovanderlinden** [comment]
This was due to an undocumented parameter `SYMFONY__CLEANSTREET__APP_PHONE_ENABLED` 

Which caused the application to trigger messagebird, but messagebird is not configured.

We added this and when this parameter is set to "false" the messagebird script is skipped and the application no longer throws the error.
